spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-3-91-139-25.compute-1.amazonaws.com:5432/d9edhih8num1ok
    username: wkadubgcfmqoqi
    password: 48c3042a288245f5e7f79c0419ae205ba4cdd804007aa621fcfb3241b28a33e1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    ##show-sql: true
server:
  port: 9080
  servlet:
    context-path: /api/
logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
