spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://ec2-50-17-21-170.compute-1.amazonaws.com:5432/dardi36jpm38v8
    username: gzorhfhmnfhcys
    password: 74a9c3bda40214ff8a00a55ae7435cd14df28978f79973d71320da2706d92ed5    
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    ##show-sql: true
server:
  port: 9080
  servlet:
    context-path: /api/
logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
